/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    FooterFixed: typeof import('./src/components/footer-fixed.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WujieVue: typeof import('@zys/wujie-vue/wujie-vue.vue')['default']
  }
}
