/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/ai/ai-assistant.vue')['default']
    AiChat: typeof import('./src/components/ai/ai-chat.vue')['default']
    AiHistory: typeof import('./src/components/ai/ai-history.vue')['default']
    AiMention: typeof import('./src/components/ai/ai-mention.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    FooterFixed: typeof import('./src/components/footer-fixed.vue')['default']
    Hover: typeof import('./src/components/hover.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/scroll.vue')['default']
    WujieVue: typeof import('@zys/wujie-vue/wujie-vue.vue')['default']
  }
}
