/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/ai/ai-assistant.vue')['default']
    AiChat: typeof import('./src/components/ai/ai-chat.vue')['default']
    AiHistory: typeof import('./src/components/ai/ai-history.vue')['default']
    AiMention: typeof import('./src/components/ai/ai-mention.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    DragNew: typeof import('./src/components/drag-new/drag-new.vue')['default']
    DragNewAside: typeof import('./src/components/drag-new/drag-new-aside.vue')['default']
    DragNewContent: typeof import('./src/components/drag-new/drag-new-content.vue')['default']
    DragNewGridRectMap: typeof import('./src/components/drag-new/drag-new-grid-rect-map.vue')['default']
    DragNewHeader: typeof import('./src/components/drag-new/drag-new-header.vue')['default']
    DragNewLayout: typeof import('./src/components/drag-new/drag-new-layout.vue')['default']
    DragNewPanel: typeof import('./src/components/drag-new/drag-new-panel.vue')['default']
    FooterFixed: typeof import('./src/components/footer-fixed.vue')['default']
    Hover: typeof import('./src/components/hover.vue')['default']
    Icon: typeof import('./src/components/drag-new/Icon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/scroll.vue')['default']
    TextContent: typeof import('./src/components/drag-new/elements/TextContent.vue')['default']
    WujieVue: typeof import('@zys/wujie-vue/wujie-vue.vue')['default']
  }
}
