# yaml 配置实例
version: '3'
services:
  chatflow:
    container_name: chatflow
    image: atorber/chatflow:latest
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - "./data:/usr/src/app"

